### PR TITLE
remove checks that do not actually make sense anymore

### LINKED ISSUE #54: check-threads-count.rb and metrics-processes-threads-count.rb fail with a `nil:NilClass` when comparing versions.
Hi,

Is there anyone else who face this issue too with check-threads-count.rb ?

````
bash-4.3# ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux-musl]
bash-4.3# bundle --version
Bundler version 1.16.0
bash-4.3# gem list sys-proctable sensu-plugins-process-checks

*** LOCAL GEMS ***

sys-proctable (0.9.8 universal-linux)

*** LOCAL GEMS ***

sensu-plugins-process-checks (2.4.0)

bash-4.3# check-threads-count.rb -c 1
Check failed to run: undefined method `version' for nil:NilClass, ["/usr/local/bundle/gems/sensu-plugins-process-checks-2.4.0/bin/check-threads-count.rb:55:in `check_proctable_version'", "/usr/local/bundle/gems/sensu-plugins-process-checks-2.4.0/bin/check-threads-count.rb:89:in `run'", "/usr/local/bundle/gems/sensu-plugin-1.3.0/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
bash-4.3# 
````

If I remove th check on this version; everything is ok : 
````
bash-4.3# sed -i "s/Gem.loaded_specs\['sys-proctable'\].*/true/" /usr/local/bundle/gems/sensu-plugins-process-checks-*/bin/*.rb
bash-4.3# check-threads-count.rb -c 1
ThreadsCount CRITICAL: 588 threads running, over threshold 1
````

Same behavior with metrics-processes-threads-count.rb if we use -t option

### PR DESCRIPTION
**Pull request by majormoses**
We previously checked if `sys-proctable` was greater than `0.9.8` when it was originally introduced in https://github.com/sensu-plugins/sensu-plugins-process-checks/commit/32044984dcb647ff63260435ebfd3d96894a26a0#diff-681f43ba752e5217d82b23a247fd5c79 it was `0.9.6` which would have fit this condition. We are currently requiring `0.9.8` which makes this check of no real value. We are now requiring `~> 1.1`.

On top of that I am not sure the [logic](https://github.com/sensu-plugins/sensu-plugins-process-checks/blob/2.5.0/bin/check-threads-count.rb#L89-L91) actually was ever correct but I don't care enough to check if that is right as it is now irrelevant.

Signed-off-by: Ben Abrams <me@benabrams.it>

## Pull Request Checklist
fixes #54 

#### General

- [ ] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### Purpose
Remove bitrot code and solve #54 at the same time.
#### Known Compatibility Issues
:man_shrugging:

### CODE REVIEW

**Comment by majormoses** [comment]
testing artifacts:
```
$ ./bin/metrics-processes-threads-count.rb -t
babrams-Serval-WS.system.process_count 416 1511836757
babrams-Serval-WS.system.thread_count 2590 1511836757

$ ./bin/check-threads-count.rb -c 1
ThreadsCount CRITICAL: 2589 threads running, over threshold 1
```

**Comment by majormoses** [comment]
@rockandska thanks for testing this. I moved your comment over here from your testing:

:warning:  **Your PR (#56 ) works too, but be aware than the update of sys-proctable seems to introduce this [bug](https://github.com/djberg96/sys-proctable/issues/64)**

Look a the time took for the check with your PR  : 
````
$ docker run -it --rm --name test-check --net host  --privileged  --pid host --ipc host 
-v /run:/run:ro 
-v /etc/localtime:/etc/localtime:ro 
-v /sys/fs/cgroup:/sys/fs/cgroup:ro 
-v /:/host:ro 
-v /var/log:/var/log 
--entrypoint /bin/sh  ruby:2.4.1-alpine3.4
/ # apk add -qU build-base curl curl-dev git libffi-dev ruby-dev ruby-io-console
/ # git clone https://github.com/sensu-plugins/sensu-plugins-process-checks.git /tmp/sensu-plugins-process-checks.git
Cloning into '/tmp/sensu-plugins-process-checks.git'...
remote: Counting objects: 593, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 593 (delta 2), reused 2 (delta 0), pack-reused 583
Receiving objects: 100% (593/593), 125.17 KiB | 0 bytes/s, done.
Resolving deltas: 100% (368/368), done.
Checking connectivity... done.
/ # cd /tmp/sensu-plugins-process-checks.git
/tmp/sensu-plugins-process-checks.git # git checkout feature/cleanup-sys-proctable
Branch feature/cleanup-sys-proctable set up to track remote branch feature/cleanup-sys-proctable from origin.
Switched to a new branch 'feature/cleanup-sys-proctable'
/tmp/sensu-plugins-process-checks.git # gem build sensu-plugins-process-checks.gemspec 
  Successfully built RubyGem
  Name: sensu-plugins-process-checks
  Version: 2.5.0
  File: sensu-plugins-process-checks-2.5.0.gem
/tmp/sensu-plugins-process-checks.git # gem install sensu-plugins-process-checks-2.5.0.gem 
Fetching: sys-proctable-1.1.5-universal-linux.gem (100%)
Successfully installed sys-proctable-1.1.5-universal-linux
Fetching: json-1.8.6.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-1.8.6
Fetching: mixlib-cli-1.7.0.gem (100%)
Successfully installed mixlib-cli-1.7.0
Fetching: sensu-plugin-1.4.5.gem (100%)
Successfully installed sensu-plugin-1.4.5
Fetching: language-0.6.0.gem (100%)
Successfully installed language-0.6.0
Fetching: english-0.6.3.gem (100%)
Successfully installed english-0.6.3
You can use the embedded Ruby by setting EMBEDDED_RUBY=true in /etc/default/sensu
Successfully installed sensu-plugins-process-checks-2.5.0
7 gems installed
/tmp/sensu-plugins-process-checks.git # gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.0)
bundler (1.15.4)
did_you_mean (1.1.0)
english (0.6.3)
io-console (default: 0.4.6)
json (default: 2.0.2, 1.8.6)
language (0.6.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
net-telnet (0.1.1)
openssl (default: 2.0.3)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
rubygems-update (2.6.13)
sensu-plugin (1.4.5)
sensu-plugins-process-checks (2.5.0)
sys-proctable (1.1.5 universal-linux)
test-unit (3.2.3)
xmlrpc (0.2.1)

/tmp/sensu-plugins-process-checks.git # time check-threads-count.rb -c 1
ThreadsCount CRITICAL: 646 threads running, over threshold 1
Command exited with non-zero status 2
real	0m 11.30s
user	0m 10.43s
sys	0m 0.83s
````

0.58s VS 11.30s :astonished:

**Comment by majormoses** [comment]
I am gonna revert the version bump and just remove the check.

**Comment by majormoses** [comment]
@rockandska if possible could I get you to test again to make sure we do not pull in the performance regression?

**Comment by rockandska** [comment]
LGTM

````
$ docker run -it --rm --name test-check --net host  --privileged  --pid host --ipc host -v /run:/run:ro -v /etc/localtime:/etc/localtime:ro -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /:/host:ro -v /var/log:/var/log --entrypoint /bin/sh  ruby:2.4.1-alpine3.4
/ # apk add -qU build-base curl curl-dev git libffi-dev ruby-dev ruby-io-console
/ # git clone https://github.com/sensu-plugins/sensu-plugins-process-checks.git /tmp/sensu-plugins-process-checks.git
Cloning into '/tmp/sensu-plugins-process-checks.git'...
remote: Counting objects: 597, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 597 (delta 5), reused 6 (delta 3), pack-reused 583
Receiving objects: 100% (597/597), 126.13 KiB | 0 bytes/s, done.
Resolving deltas: 100% (371/371), done.
Checking connectivity... done.
/ # cd /tmp/sensu-plugins-process-checks.git
/tmp/sensu-plugins-process-checks.git # git checkout feature/cleanup-sys-proctable
Branch feature/cleanup-sys-proctable set up to track remote branch feature/cleanup-sys-proctable from origin.
Switched to a new branch 'feature/cleanup-sys-proctable'
/tmp/sensu-plugins-process-checks.git # gem build sensu-plugins-process-checks.gemspec
  Successfully built RubyGem
  Name: sensu-plugins-process-checks
  Version: 2.5.0
  File: sensu-plugins-process-checks-2.5.0.gem
/tmp/sensu-plugins-process-checks.git # gem install sensu-plugins-process-checks-2.5.0.gem
Fetching: sys-proctable-0.9.9-universal-linux.gem (100%)
Successfully installed sys-proctable-0.9.9-universal-linux
Fetching: json-1.8.6.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-1.8.6
Fetching: mixlib-cli-1.7.0.gem (100%)
Successfully installed mixlib-cli-1.7.0
Fetching: sensu-plugin-1.4.5.gem (100%)
Successfully installed sensu-plugin-1.4.5
Fetching: language-0.6.0.gem (100%)
Successfully installed language-0.6.0
Fetching: english-0.6.3.gem (100%)
Successfully installed english-0.6.3
You can use the embedded Ruby by setting EMBEDDED_RUBY=true in /etc/default/sensu
Successfully installed sensu-plugins-process-checks-2.5.0
7 gems installed
/tmp/sensu-plugins-process-checks.git # gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.0)
bundler (1.15.4)
did_you_mean (1.1.0)
english (0.6.3)
io-console (default: 0.4.6)
json (default: 2.0.2, 1.8.6)
language (0.6.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
net-telnet (0.1.1)
openssl (default: 2.0.3)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
rubygems-update (2.6.13)
sensu-plugin (1.4.5)
sensu-plugins-process-checks (2.5.0)
sys-proctable (0.9.9 universal-linux)
test-unit (3.2.3)
xmlrpc (0.2.1)
/tmp/sensu-plugins-process-checks.git # time check-threads-count.rb -c 1
ThreadsCount CRITICAL: 684 threads running, over threshold 1
Command exited with non-zero status 2
real	0m 0.69s
user	0m 0.55s
sys	0m 0.13s
/tmp/sensu-plugins-process-checks.git # time check-threads-count.rb -c 1
ThreadsCount CRITICAL: 684 threads running, over threshold 1
Command exited with non-zero status 2
real	0m 0.67s
user	0m 0.54s
sys	0m 0.12s
/tmp/sensu-plugins-process-checks.git # 
````
